### ISSUE TITLE
Add TM/HM Queries

### ISSUE THREAD

**Issue by LokiFrostGiant** [JacobJanzen/J5-Pocket-Monsters-Database#68]
I have added a few queries involving retrieving TM lists and HM lists, under Wave 3 header in Move queries. 

Needs to be added to the project. Only assigning all of you because it affects all parts. Thank you!

**Comment by dlarocque** [comment]
> I've added the queries to the front-end, just need the api endpoints to be completed I added the sql to the backend file and made the routing links which I referenced in the frontend, so let me know if the routing changes

Added to the backend #95 
Can you double-check to make sure it's good?
